export const defaultImages = [
  {
    id: "R5S4OQpG0lE",
    slug: "concrete-bridge-near-mountains-during-daytime-R5S4OQpG0lE",
    alternative_slugs: {
      en: "concrete-bridge-near-mountains-during-daytime-R5S4OQpG0lE",
      es: "puente-de-hormigon-cerca-de-las-montanas-durante-el-dia-R5S4OQpG0lE",
      ja: "昼間の山間部のコンクリート橋-R5S4OQpG0lE",
      fr: "pont-en-beton-pres-des-montagnes-pendant-la-journee-R5S4OQpG0lE",
      it: "ponte-di-cemento-vicino-alle-montagne-durante-il-giorno-R5S4OQpG0lE",
      ko: "낮에는-산-근처의-콘크리트-다리-R5S4OQpG0lE",
      de: "betonbrucke-in-der-nahe-von-bergen-tagsuber-R5S4OQpG0lE",
      pt: "ponte-de-concreto-perto-das-montanhas-durante-o-dia-R5S4OQpG0lE",
    },
    created_at: "2014-09-24T06:41:57Z",
    updated_at: "2024-05-08T01:01:06Z",
    promoted_at: "2014-09-24T06:41:57Z",
    width: 4288,
    height: 2848,
    color: "#262626",
    blur_hash: "LbCGlJIBM{oz_MIVM{of?aV[RjWC",
    description: null,
    alt_description: "concrete bridge near mountains during daytime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/uploads/14115408840644deb16b0/2dc933e3?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/uploads/14115408840644deb16b0/2dc933e3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/uploads/14115408840644deb16b0/2dc933e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/uploads/14115408840644deb16b0/2dc933e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/uploads/14115408840644deb16b0/2dc933e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/uploads/14115408840644deb16b0/2dc933e3",
    },
    links: {
      self: "https://api.unsplash.com/photos/concrete-bridge-near-mountains-during-daytime-R5S4OQpG0lE",
      html: "https://unsplash.com/photos/concrete-bridge-near-mountains-during-daytime-R5S4OQpG0lE",
      download:
        "https://unsplash.com/photos/R5S4OQpG0lE/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/R5S4OQpG0lE/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 775,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "yXNctCcISxs",
      updated_at: "2023-12-09T04:46:52Z",
      username: "caseyfyfe",
      name: "Casey Fyfe",
      first_name: "Casey",
      last_name: "Fyfe",
      twitter_username: "caseyfyfe_",
      portfolio_url: "https://opensea.io/HiFyfe",
      bio: "Now selling my photos as 1/1 NFT's! \r\nhttps://opensea.io/HiFyfe",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/caseyfyfe",
        html: "https://unsplash.com/@caseyfyfe",
        photos: "https://api.unsplash.com/users/caseyfyfe/photos",
        likes: "https://api.unsplash.com/users/caseyfyfe/likes",
        portfolio: "https://api.unsplash.com/users/caseyfyfe/portfolio",
        following: "https://api.unsplash.com/users/caseyfyfe/following",
        followers: "https://api.unsplash.com/users/caseyfyfe/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1641509837878-a4d2316bbbe8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1641509837878-a4d2316bbbe8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1641509837878-a4d2316bbbe8image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "hifyfe",
      total_collections: 0,
      total_likes: 1,
      total_photos: 7,
      total_promoted_photos: 5,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: "hifyfe",
        portfolio_url: "https://opensea.io/HiFyfe",
        twitter_username: "caseyfyfe_",
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D300",
      name: "NIKON CORPORATION, NIKON D300",
      exposure_time: "1/250",
      aperture: "3.2",
      focal_length: "56.0",
      iso: 250,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 16633383,
    downloads: 115411,
  },
  {
    id: "6wQId4r0uA4",
    slug: "white-and-brown-concrete-apartment-6wQId4r0uA4",
    alternative_slugs: {
      en: "white-and-brown-concrete-apartment-6wQId4r0uA4",
      es: "apartamento-de-hormigon-blanco-y-marron-6wQId4r0uA4",
      ja: "白と茶色のコンクリートのアパート-6wQId4r0uA4",
      fr: "appartement-en-beton-blanc-et-marron-6wQId4r0uA4",
      it: "appartamento-in-cemento-bianco-e-marrone-6wQId4r0uA4",
      ko: "흰색과-갈색-콘크리트-아파트-6wQId4r0uA4",
      de: "wohnung-aus-weissem-und-braunem-beton-6wQId4r0uA4",
      pt: "apartamento-de-concreto-branco-e-marrom-6wQId4r0uA4",
    },
    created_at: "2016-04-23T11:10:57Z",
    updated_at: "2024-05-08T01:00:48Z",
    promoted_at: "2016-04-23T11:10:57Z",
    width: 3692,
    height: 2462,
    color: "#c0c0c0",
    blur_hash: "LLFPEGM{00xvxuj?jZWXIUaeofa}",
    description: null,
    alt_description: "white and brown concrete apartment",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1461409971633-aa0e46732112?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1461409971633-aa0e46732112?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1461409971633-aa0e46732112?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1461409971633-aa0e46732112?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1461409971633-aa0e46732112?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1461409971633-aa0e46732112",
    },
    links: {
      self: "https://api.unsplash.com/photos/white-and-brown-concrete-apartment-6wQId4r0uA4",
      html: "https://unsplash.com/photos/white-and-brown-concrete-apartment-6wQId4r0uA4",
      download:
        "https://unsplash.com/photos/6wQId4r0uA4/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/6wQId4r0uA4/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 717,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "7IfMAs9CZGA",
      updated_at: "2023-09-13T05:15:50Z",
      username: "chuchad",
      name: "Vladimir Chuchadeev",
      first_name: "Vladimir",
      last_name: "Chuchadeev",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: "Vladimir, Russia",
      links: {
        self: "https://api.unsplash.com/users/chuchad",
        html: "https://unsplash.com/@chuchad",
        photos: "https://api.unsplash.com/users/chuchad/photos",
        likes: "https://api.unsplash.com/users/chuchad/likes",
        portfolio: "https://api.unsplash.com/users/chuchad/portfolio",
        following: "https://api.unsplash.com/users/chuchad/following",
        followers: "https://api.unsplash.com/users/chuchad/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1461506867020-850c40dced27?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1461506867020-850c40dced27?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1461506867020-850c40dced27?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 26,
      total_photos: 18,
      total_promoted_photos: 5,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS-1D Mark III",
      name: "Canon, EOS-1D Mark III",
      exposure_time: "1/640",
      aperture: "4.0",
      focal_length: "91.0",
      iso: 500,
    },
    location: {
      name: "Vladimir, Russia",
      city: "Vladimir",
      country: "Russia",
      position: {
        latitude: 56.1445956,
        longitude: 40.4178686,
      },
    },
    views: 14435997,
    downloads: 57885,
  },
  {
    id: "vZS8LSZ1KZs",
    slug: "time-lapse-photography-of-waterfall-leading-to-ocean-vZS8LSZ1KZs",
    alternative_slugs: {
      en: "time-lapse-photography-of-waterfall-leading-to-ocean-vZS8LSZ1KZs",
      es: "fotografia-de-lapso-de-tiempo-de-la-cascada-que-conduce-al-oceano-vZS8LSZ1KZs",
      ja: "海に通じる滝のタイムラプス撮影-vZS8LSZ1KZs",
      fr: "photographie-en-accelere-de-la-chute-deau-menant-a-locean-vZS8LSZ1KZs",
      it: "fotografia-time-lapse-della-cascata-che-conduce-alloceano-vZS8LSZ1KZs",
      ko: "바다로-이어지는-폭포의-타임랩스-사진-vZS8LSZ1KZs",
      de: "zeitrafferfotografie-eines-wasserfalls-der-zum-meer-fuhrt-vZS8LSZ1KZs",
      pt: "fotografia-time-lapse-de-cachoeira-levando-ao-oceano-vZS8LSZ1KZs",
    },
    created_at: "2018-04-28T17:08:45Z",
    updated_at: "2024-06-29T15:18:28Z",
    promoted_at: "2018-04-29T15:32:44Z",
    width: 2550,
    height: 1600,
    color: "#d9d9d9",
    blur_hash: "LoI}*E%Nxut7~qRiRkWB?aofafWB",
    description:
      "This was taken on the first day of our 2017 photo workshop to the Faroe Islands. For the first time ever we saw snow on the roads on the Faroe Islands when we landed and it kept there for 2 days which gave us some incredible new opportunities.\r\n\r\nWe had about 15 m/s winds and at a point the waterfall seemed to be turning around - the water was going up instead of down. Incredible and majestic to watch - both through the lens and with your eyes!",
    alt_description: "time lapse photography of waterfall leading to ocean",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1524934992636-ce0dc0e253bc?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1524934992636-ce0dc0e253bc?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1524934992636-ce0dc0e253bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1524934992636-ce0dc0e253bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1524934992636-ce0dc0e253bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1524934992636-ce0dc0e253bc",
    },
    links: {
      self: "https://api.unsplash.com/photos/time-lapse-photography-of-waterfall-leading-to-ocean-vZS8LSZ1KZs",
      html: "https://unsplash.com/photos/time-lapse-photography-of-waterfall-leading-to-ocean-vZS8LSZ1KZs",
      download:
        "https://unsplash.com/photos/vZS8LSZ1KZs/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/vZS8LSZ1KZs/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 594,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "HjC6bcxHW4I",
      updated_at: "2024-05-06T18:54:58Z",
      username: "strikert",
      name: "Hans Christian Strikert",
      first_name: "Hans Christian",
      last_name: "Strikert",
      twitter_username: null,
      portfolio_url: "https://www.northernworkshop.com",
      bio: "I'm primarily a landscape and wildlife photographer from Denmark. I have a rather long career in photography and I host photo workshops on the Faroe Islands every year. \r\nPlease contact me if you are interested in working together.",
      location: "Denmark",
      links: {
        self: "https://api.unsplash.com/users/strikert",
        html: "https://unsplash.com/@strikert",
        photos: "https://api.unsplash.com/users/strikert/photos",
        likes: "https://api.unsplash.com/users/strikert/likes",
        portfolio: "https://api.unsplash.com/users/strikert/portfolio",
        following: "https://api.unsplash.com/users/strikert/following",
        followers: "https://api.unsplash.com/users/strikert/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-fb-1524851085-2df986cadfc0.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-fb-1524851085-2df986cadfc0.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-fb-1524851085-2df986cadfc0.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "hanschristianstrikert",
      total_collections: 0,
      total_likes: 0,
      total_photos: 2,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: "hanschristianstrikert",
        portfolio_url: "https://www.northernworkshop.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 5DS",
      name: "Canon, EOS 5DS",
      exposure_time: "1/250",
      aperture: "8.0",
      focal_length: "21.0",
      iso: 100,
    },
    location: {
      name: "Gasadalur, Faroe Islands",
      city: "Gasadalur",
      country: "Faroe Islands",
      position: {
        latitude: 62.1051890165941,
        longitude: -7.43602174865714,
      },
    },
    views: 6102069,
    downloads: 3381,
  },
  {
    id: "1fWKY6ukL-E",
    slug: "a-black-and-white-photo-of-a-moon-1fWKY6ukL-E",
    alternative_slugs: {
      en: "a-black-and-white-photo-of-a-moon-1fWKY6ukL-E",
      es: "una-foto-en-blanco-y-negro-de-una-luna-1fWKY6ukL-E",
      ja: "月の白黒写真-1fWKY6ukL-E",
      fr: "une-photo-en-noir-et-blanc-dune-lune-1fWKY6ukL-E",
      it: "una-foto-in-bianco-e-nero-di-una-luna-1fWKY6ukL-E",
      ko: "달의-흑백-사진-1fWKY6ukL-E",
      de: "ein-schwarz-weiss-foto-eines-mondes-1fWKY6ukL-E",
      pt: "uma-foto-em-preto-e-branco-de-uma-lua-1fWKY6ukL-E",
    },
    created_at: "2024-01-13T14:21:06Z",
    updated_at: "2024-06-07T23:53:02Z",
    promoted_at: "2024-01-15T07:17:56Z",
    width: 2480,
    height: 3508,
    color: "#262626",
    blur_hash: "L57KuK9F9F_3_2WBE1%L01?axu9G",
    description: "Art by Jaquieu - You can buy this print, send me a message.",
    alt_description: "a black and white photo of a moon",
    breadcrumbs: [
      {
        slug: "backgrounds",
        title: "HQ Background Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "art",
        title: "Art Backgrounds",
        index: 1,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1705154580249-55990fe3a8fb?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1705154580249-55990fe3a8fb?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1705154580249-55990fe3a8fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1705154580249-55990fe3a8fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1705154580249-55990fe3a8fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1705154580249-55990fe3a8fb",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-black-and-white-photo-of-a-moon-1fWKY6ukL-E",
      html: "https://unsplash.com/photos/a-black-and-white-photo-of-a-moon-1fWKY6ukL-E",
      download:
        "https://unsplash.com/photos/1fWKY6ukL-E/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/1fWKY6ukL-E/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 212,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "cpS-BeZLkmQ",
      updated_at: "2024-06-28T11:41:59Z",
      username: "andreicastanha",
      name: "Andrei J Castanha",
      first_name: "Andrei",
      last_name: "J Castanha",
      twitter_username: "jaquieu",
      portfolio_url: "http://instagram.com/@andreicastanha",
      bio: "Hello. Its good to see you here. Hope my visions can be helpful.\r\n If you like my work, https://www.buymeacoffee.com/andreicastanha",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/andreicastanha",
        html: "https://unsplash.com/@andreicastanha",
        photos: "https://api.unsplash.com/users/andreicastanha/photos",
        likes: "https://api.unsplash.com/users/andreicastanha/likes",
        portfolio: "https://api.unsplash.com/users/andreicastanha/portfolio",
        following: "https://api.unsplash.com/users/andreicastanha/following",
        followers: "https://api.unsplash.com/users/andreicastanha/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-fb-1489753166-891739cbbd67.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-fb-1489753166-891739cbbd67.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-fb-1489753166-891739cbbd67.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "andreicastanha",
      total_collections: 27,
      total_likes: 29,
      total_photos: 144,
      total_promoted_photos: 9,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "andreicastanha",
        portfolio_url: "http://instagram.com/@andreicastanha",
        twitter_username: "jaquieu",
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: 0,
        longitude: 0,
      },
    },
    views: 7462051,
    downloads: 128833,
  },
  {
    id: "_SFJhRPzJHs",
    slug: "satellite-view-of-earths-surface-_SFJhRPzJHs",
    alternative_slugs: {
      en: "satellite-view-of-earths-surface-_SFJhRPzJHs",
      es: "vista-satelital-de-la-superficie-de-la-tierra-_SFJhRPzJHs",
      ja: "地表の衛星写真-_SFJhRPzJHs",
      fr: "vue-satellite-de-la-surface-de-la-terre-_SFJhRPzJHs",
      it: "vista-satellitare-della-superficie-terrestre-_SFJhRPzJHs",
      ko: "지구-표면의-위성-보기-_SFJhRPzJHs",
      de: "satellitenaufnahme-der-erdoberflache-_SFJhRPzJHs",
      pt: "vista-de-satelite-da-superficie-da-terra-_SFJhRPzJHs",
    },
    created_at: "2015-11-06T02:28:23Z",
    updated_at: "2024-06-29T09:00:54Z",
    promoted_at: "2015-11-06T02:28:23Z",
    width: 4928,
    height: 3280,
    color: "#594026",
    blur_hash: "L8Acbut79GE2$*xZIpR*0fjYxut7",
    description: "On top of the world",
    alt_description: "satellite view of earth's surface",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1446776899648-aa78eefe8ed0?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1446776899648-aa78eefe8ed0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1446776899648-aa78eefe8ed0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1446776899648-aa78eefe8ed0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1446776899648-aa78eefe8ed0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1446776899648-aa78eefe8ed0",
    },
    links: {
      self: "https://api.unsplash.com/photos/satellite-view-of-earths-surface-_SFJhRPzJHs",
      html: "https://unsplash.com/photos/satellite-view-of-earths-surface-_SFJhRPzJHs",
      download:
        "https://unsplash.com/photos/_SFJhRPzJHs/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/_SFJhRPzJHs/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 5228,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "approved",
        approved_on: "2021-02-22T16:03:09Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "XpI7t2xRxfM",
      updated_at: "2024-06-29T15:52:01Z",
      username: "nasa",
      name: "NASA",
      first_name: "NASA",
      last_name: null,
      twitter_username: null,
      portfolio_url: "http://www.nasa.gov/",
      bio: "To reach for new heights and reveal the unknown so that what we do and learn will benefit all humankind.",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/nasa",
        html: "https://unsplash.com/@nasa",
        photos: "https://api.unsplash.com/users/nasa/photos",
        likes: "https://api.unsplash.com/users/nasa/likes",
        portfolio: "https://api.unsplash.com/users/nasa/portfolio",
        following: "https://api.unsplash.com/users/nasa/following",
        followers: "https://api.unsplash.com/users/nasa/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1446819291540-625b8478e701?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1446819291540-625b8478e701?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1446819291540-625b8478e701?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 1,
      total_likes: 0,
      total_photos: 73,
      total_promoted_photos: 37,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: "http://www.nasa.gov/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D4",
      name: "NIKON CORPORATION, NIKON D4",
      exposure_time: "1/8",
      aperture: "2.8",
      focal_length: "400.0",
      iso: 5600,
    },
    location: {
      name: "Manhattan, New York City, United States",
      city: "New York City",
      country: "United States",
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 75127932,
    downloads: 584181,
  },
  {
    id: "cvOidhGZW7A",
    slug: "aerial-photography-of-mountain-cvOidhGZW7A",
    alternative_slugs: {
      en: "aerial-photography-of-mountain-cvOidhGZW7A",
      es: "fotografia-aerea-de-montana-cvOidhGZW7A",
      ja: "山の航空写真-cvOidhGZW7A",
      fr: "photographie-aerienne-de-montagne-cvOidhGZW7A",
      it: "fotografia-aerea-di-montagna-cvOidhGZW7A",
      ko: "산의-항공-사진-cvOidhGZW7A",
      de: "luftaufnahmen-von-bergen-cvOidhGZW7A",
      pt: "fotografia-aerea-de-montanha-cvOidhGZW7A",
    },
    created_at: "2019-01-30T13:13:23Z",
    updated_at: "2024-06-29T12:14:44Z",
    promoted_at: "2019-02-01T07:48:51Z",
    width: 3058,
    height: 4587,
    color: "#262626",
    blur_hash: "LkHUd]s.M{oe~Voej@oLofa#s:j@",
    description: null,
    alt_description: "aerial photography of mountain",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "nature",
        title: "Nature Images",
        index: 1,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1548853879-e3135725174c?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1548853879-e3135725174c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1548853879-e3135725174c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1548853879-e3135725174c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1548853879-e3135725174c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1548853879-e3135725174c",
    },
    links: {
      self: "https://api.unsplash.com/photos/aerial-photography-of-mountain-cvOidhGZW7A",
      html: "https://unsplash.com/photos/aerial-photography-of-mountain-cvOidhGZW7A",
      download:
        "https://unsplash.com/photos/cvOidhGZW7A/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/cvOidhGZW7A/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 295,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "P9cpS1fJFN8",
      updated_at: "2024-06-25T21:34:16Z",
      username: "conti_photos",
      name: "Fabrizio Conti",
      first_name: "Fabrizio",
      last_name: "Conti",
      twitter_username: null,
      portfolio_url: "https://conti.photos/",
      bio: "Italian based web developer passionate about photography | Mountain | Nature | Landscapes",
      location: "italy",
      links: {
        self: "https://api.unsplash.com/users/conti_photos",
        html: "https://unsplash.com/@conti_photos",
        photos: "https://api.unsplash.com/users/conti_photos/photos",
        likes: "https://api.unsplash.com/users/conti_photos/likes",
        portfolio: "https://api.unsplash.com/users/conti_photos/portfolio",
        following: "https://api.unsplash.com/users/conti_photos/following",
        followers: "https://api.unsplash.com/users/conti_photos/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1572299392726-a7e48483eea4image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1572299392726-a7e48483eea4image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1572299392726-a7e48483eea4image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "fabricont",
      total_collections: 23,
      total_likes: 815,
      total_photos: 251,
      total_promoted_photos: 133,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "fabricont",
        portfolio_url: "https://conti.photos/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon PowerShot G5 X",
      name: "Canon, PowerShot G5 X",
      exposure_time: "1/2000",
      aperture: "11.0",
      focal_length: "24.8",
      iso: 400,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 4854048,
    downloads: 9375,
  },
  {
    id: "wgeTD37mGN4",
    slug: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
    alternative_slugs: {
      en: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      es: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      ja: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      fr: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      it: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      ko: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      de: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      pt: "a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
    },
    created_at: "2023-11-05T13:21:58Z",
    updated_at: "2024-06-28T23:52:48Z",
    promoted_at: "2023-11-16T09:16:01Z",
    width: 9600,
    height: 5400,
    color: "#738c73",
    blur_hash: "L5DmdB-T4TM|My-ntPM{tRIUbsNM",
    description: null,
    alt_description: "a lot of green and white vases stacked on top of each other",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "nature",
        title: "Nature Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "seascape",
        title: "Seascape Pictures",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1699190375905-3cac33bbdbb1?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1699190375905-3cac33bbdbb1?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1699190375905-3cac33bbdbb1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1699190375905-3cac33bbdbb1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1699190375905-3cac33bbdbb1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1699190375905-3cac33bbdbb1",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      html: "https://unsplash.com/photos/a-lot-of-green-and-white-vases-stacked-on-top-of-each-other-wgeTD37mGN4",
      download:
        "https://unsplash.com/photos/wgeTD37mGN4/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/wgeTD37mGN4/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 148,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "3d-renders": {
        status: "approved",
        approved_on: "2024-03-13T08:50:10Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "QIwoINLgpsA",
      updated_at: "2024-06-30T00:02:28Z",
      username: "brave4_heart",
      name: "Jigar Panchal",
      first_name: "Jigar",
      last_name: "Panchal",
      twitter_username: "Jigar04022000",
      portfolio_url: "https://panchaljigar1000.wixsite.com/jigar-panchal",
      bio: "Gods plan is always better than your plan ✨✨",
      location: "Surat, Gujarat, India",
      links: {
        self: "https://api.unsplash.com/users/brave4_heart",
        html: "https://unsplash.com/@brave4_heart",
        photos: "https://api.unsplash.com/users/brave4_heart/photos",
        likes: "https://api.unsplash.com/users/brave4_heart/likes",
        portfolio: "https://api.unsplash.com/users/brave4_heart/portfolio",
        following: "https://api.unsplash.com/users/brave4_heart/following",
        followers: "https://api.unsplash.com/users/brave4_heart/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1696093955329-a12ce8a17180image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1696093955329-a12ce8a17180image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1696093955329-a12ce8a17180image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "crash.tags",
      total_collections: 2,
      total_likes: 1175,
      total_photos: 612,
      total_promoted_photos: 87,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "crash.tags",
        portfolio_url: "https://panchaljigar1000.wixsite.com/jigar-panchal",
        twitter_username: "Jigar04022000",
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: "Surat, Gujarat, India",
      city: "Surat",
      country: "India",
      position: {
        latitude: 21.17024,
        longitude: 72.831061,
      },
    },
    views: 7926237,
    downloads: 74016,
  },
  {
    id: "YbgPWfWlvkE",
    slug: "green-grass-field-and-brown-soil-YbgPWfWlvkE",
    alternative_slugs: {
      en: "green-grass-field-and-brown-soil-YbgPWfWlvkE",
      es: "campo-de-hierba-verde-y-tierra-marron-YbgPWfWlvkE",
      ja: "緑の芝生と茶色の土壌-YbgPWfWlvkE",
      fr: "champ-dherbe-verte-et-terre-brune-YbgPWfWlvkE",
      it: "campo-di-erba-verde-e-terreno-marrone-YbgPWfWlvkE",
      ko: "푸른-잔디밭과-갈색-토양-YbgPWfWlvkE",
      de: "grunes-grasfeld-und-braune-erde-YbgPWfWlvkE",
      pt: "campo-de-grama-verde-e-solo-marrom-YbgPWfWlvkE",
    },
    created_at: "2015-06-01T18:57:17Z",
    updated_at: "2024-06-15T00:21:23Z",
    promoted_at: "2015-06-01T18:57:17Z",
    width: 3264,
    height: 2448,
    color: "#f3f3f3",
    blur_hash: "L|Mjp,sCWUbG_NW.jZoLR-WVofj[",
    description:
      "Brown and green fields / follow me on https://www.instagram.com/california_latte/ for more images like this.",
    alt_description: "green grass field and brown soil",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "nature",
        title: "Nature Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "landscape",
        title: "Landscape Images & Pictures",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1433185000771-ec45c869c61b?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1433185000771-ec45c869c61b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1433185000771-ec45c869c61b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1433185000771-ec45c869c61b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1433185000771-ec45c869c61b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1433185000771-ec45c869c61b",
    },
    links: {
      self: "https://api.unsplash.com/photos/green-grass-field-and-brown-soil-YbgPWfWlvkE",
      html: "https://unsplash.com/photos/green-grass-field-and-brown-soil-YbgPWfWlvkE",
      download:
        "https://unsplash.com/photos/YbgPWfWlvkE/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/YbgPWfWlvkE/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 2063,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "bvW5Cgpe-Es",
      updated_at: "2024-05-22T04:16:55Z",
      username: "elizabethlies",
      name: "elizabeth lies",
      first_name: "elizabeth",
      last_name: "lies",
      twitter_username: "california_latte",
      portfolio_url: "https://www.instagram.com/california_latte/",
      bio: "I now travel solo with my camper van.",
      location: "barcelona",
      links: {
        self: "https://api.unsplash.com/users/elizabethlies",
        html: "https://unsplash.com/@elizabethlies",
        photos: "https://api.unsplash.com/users/elizabethlies/photos",
        likes: "https://api.unsplash.com/users/elizabethlies/likes",
        portfolio: "https://api.unsplash.com/users/elizabethlies/portfolio",
        following: "https://api.unsplash.com/users/elizabethlies/following",
        followers: "https://api.unsplash.com/users/elizabethlies/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1445586430794-b7cfbed43358?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1445586430794-b7cfbed43358?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1445586430794-b7cfbed43358?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "california_latte",
      total_collections: 2,
      total_likes: 11,
      total_photos: 37,
      total_promoted_photos: 25,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "california_latte",
        portfolio_url: "https://www.instagram.com/california_latte/",
        twitter_username: "california_latte",
        paypal_email: null,
      },
    },
    exif: {
      make: "Apple",
      model: "iPhone 5s",
      name: "Apple, iPhone 5s",
      exposure_time: "1/302",
      aperture: "2.2",
      focal_length: "4.2",
      iso: 32,
    },
    location: {
      name: "Unnamed Road, 49722 El Perdigón, Zamora, Spain, El Perdigón",
      city: "El Perdigón",
      country: "Spain",
      position: {
        latitude: 41.40985,
        longitude: -5.78555833,
      },
    },
    views: 22487916,
    downloads: 189072,
  },
  {
    id: "WIjAntqQIrI",
    slug: "birds-eye-view-photography-of-mountain-surrounded-with-fog-WIjAntqQIrI",
    alternative_slugs: {
      en: "birds-eye-view-photography-of-mountain-surrounded-with-fog-WIjAntqQIrI",
      es: "fotografia-a-vista-de-pajaro-de-la-montana-rodeada-de-niebla-WIjAntqQIrI",
      ja: "霧に包まれた山の鳥瞰写真-WIjAntqQIrI",
      fr: "photographie-a-vol-doiseau-dune-montagne-entouree-de-brouillard-WIjAntqQIrI",
      it: "fotografia-a-volo-duccello-della-montagna-circondata-da-nebbia-WIjAntqQIrI",
      ko: "안개에-둘러싸인-산의-조감도-사진-WIjAntqQIrI",
      de: "fotografie-aus-der-vogelperspektive-von-bergen-umgeben-von-nebel-WIjAntqQIrI",
      pt: "birds-eye-view-fotografia-da-montanha-cercada-de-nevoeiro-WIjAntqQIrI",
    },
    created_at: "2017-07-26T01:02:25Z",
    updated_at: "2024-06-29T21:05:13Z",
    promoted_at: "2017-07-27T11:05:50Z",
    width: 6664,
    height: 4443,
    color: "#262626",
    blur_hash: "LiGIWONGM{xZ_4NGR%flkrWVWUWC",
    description: null,
    alt_description: "bird's eye-view photography of mountain surrounded with fog",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "stock",
        title: "Stock Photos & Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cover",
        title: "Cover Photos & Images",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1501030834146-c0b1914e72be?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1501030834146-c0b1914e72be?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1501030834146-c0b1914e72be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1501030834146-c0b1914e72be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1501030834146-c0b1914e72be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1501030834146-c0b1914e72be",
    },
    links: {
      self: "https://api.unsplash.com/photos/birds-eye-view-photography-of-mountain-surrounded-with-fog-WIjAntqQIrI",
      html: "https://unsplash.com/photos/birds-eye-view-photography-of-mountain-surrounded-with-fog-WIjAntqQIrI",
      download:
        "https://unsplash.com/photos/WIjAntqQIrI/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
      download_location:
        "https://api.unsplash.com/photos/WIjAntqQIrI/download?ixid=M3w2MjgxNjh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk3MDk5ODV8",
    },
    likes: 865,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: "approved",
        approved_on: "2024-03-26T19:26:52Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "gGmJMN_AUww",
      updated_at: "2024-06-25T06:28:05Z",
      username: "timmarshall",
      name: "Tim Marshall",
      first_name: "Tim",
      last_name: "Marshall",
      twitter_username: null,
      portfolio_url: "http://instagram.com/timmarshall.nz",
      bio: null,
      location: "Auckland, New Zealand",
      links: {
        self: "https://api.unsplash.com/users/timmarshall",
        html: "https://unsplash.com/@timmarshall",
        photos: "https://api.unsplash.com/users/timmarshall/photos",
        likes: "https://api.unsplash.com/users/timmarshall/likes",
        portfolio: "https://api.unsplash.com/users/timmarshall/portfolio",
        following: "https://api.unsplash.com/users/timmarshall/following",
        followers: "https://api.unsplash.com/users/timmarshall/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1652677754823-401f02493545image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1652677754823-401f02493545image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1652677754823-401f02493545image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "timmarshall.nz",
      total_collections: 0,
      total_likes: 0,
      total_photos: 159,
      total_promoted_photos: 91,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "timmarshall.nz",
        portfolio_url: "http://instagram.com/timmarshall.nz",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 5D Mark IV",
      name: "Canon, EOS 5D Mark IV",
      exposure_time: "1/8000",
      aperture: "1.4",
      focal_length: "35.0",
      iso: 100,
    },
    location: {
      name: "Treble Cone, New Zealand",
      city: "Treble Cone",
      country: "New Zealand",
      position: {
        latitude: -44.6347951,
        longitude: 168.8972227,
      },
    },
    views: 13572972,
    downloads: 248590,
  },
];
